### PR TITLE
Update for 3.0

### PR DESCRIPTION
**Pull request by EmilyDimpfl**
I think this should be a complete update for the new patch, from work on https://github.com/Josemanki/dofuslab-items/commits/dofus3/

firefox_2024-12-05_02-55-46

### CODE REVIEW

**Comment by EmilyDimpfl** [comment]
Looks like I brought back the -AP/-MP bug on weapons. Fixing shortly.

**Comment by EmilyDimpfl** [comment]
There are some additional issues I discovered with "healing" lines on weapons.

GitHubDesktop_2024-12-05_04-15-39

**Comment by EmilyDimpfl** [comment]
While looking through data, I noticed a couple new active weapon effects:
- Bounihime has a "Steals MP" effect
- Mama Ayuto's Rolling Pin has a "Pushes back cell" effect
- Dark Vlad's Flamberge has a "Pushes back cell" effect

I don't think we currently support these. How much trouble is it to add new effects?

**Comment by Josemanki** [comment]
Adding new effects should not be the worst thing ever but modifies enums which we had problems with before when adding elemental heals for some reason. I can prepare a PR for the new effects but we'll need @lightyearsaway to massage those effects in again :/.

**Review by Josemanki — APPROVED** [review]

**Pull request merged**
