### PR TITLE
feat: add cs-CZ localization

### PR DESCRIPTION
**Pull request by tomasvn**
- add new localization, cs-CZ

### CODE REVIEW

**Comment by lightyearsaway** [comment]
Hey, thanks for the PR! This is Czech, right? Originally, our plan was to support only the 6 languages that Dofus supports (to my knowledge), which I thought were English, French, Spanish, Italian, Portuguese, and German. Does Dofus support Czech? And if not, what do you expect the names of the items, classes, spells, and other game-related terms to show up in?

**Comment by tomasvn** [comment]
Yup. Isn’t this just for the interface of the web app? And dofus doesn’t support czech by default, but the czech comunity in dofus is actually quite large, they either can use the english translation or the czech translation of the web app, and I like the project and wanted to contribute to open source

**Comment by tomasvn** [comment]
Not every string I have translated, some I have left untouched by default, as it wouldn’t make sense in czech

**Comment by lightyearsaway** [comment]
If you still want to see this through, can we discuss on Discord (Germy#9001) or somewhere a little more convenient? I (and I think @samlee405 as well) have some reservations about this mixed-language UI approach.

**Pull request closed without merging**
